config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :models
  resources :friends
  get 'home/about'
  root 'home#index'
  get 'home/contact'
  # get 'home/about'
  # # get "/home", to: "home/about"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end 
  def about
  end
  def contact
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: %i[ show edit update destroy ]

  # GET /models or /models.json
  def index
    @models = Model.all
  end

  # GET /models/1 or /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models or /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to model_url(@model), notice: "Model was successfully created." }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1 or /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to model_url(@model), notice: "Model was successfully updated." }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1 or /models/1.json
  def destroy
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url, notice: "Model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def model_params
      params.require(:model).permit(:Buddies, :first_name, :last_name, :email, :phone, :twitter)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <% form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div><br/>

  <div class="form-group">
    <% form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div><br/>

  <div class="form-group">
    <% form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email@example.com" %>
  </div><br/>

  <div class="form-group">
    <% form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone No" %>
  </div><br/>

  <div class="form-group">
    <% form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control",placeholder:"Twitter User Name" %>
  </div>

  <div ><br/>
    <%= form.submit class:"btn btn-success" %>
  </div>
  
<% end %>

app/views/friends/_friend.html.erb
<br/><div id="<%= dom_id friend %>">
<table class="table table-hover table-bordered">
    <thead class="bg-dark text-white">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Twitter</th>
        </tr>
    </thead>
      <tr>
          <tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
        </tr>
    </tr>
</table>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-primary" %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
<br/></div>

app/views/friends/index.html.erb
<h1>Friend List</h1>
<div id="friends">
  
  <% @friends.each do |friend| %>
    <%= render friend %>
    
      <br/>
      <%= link_to "Show this friend", friend, class:"btn btn-primary" %><br/>
      
    
  <% end %>
  
</div><br/>

<%= link_to "New friend", new_friend_path, class:'btn btn-primary' %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <br/>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-primary" %> | 
  <%= link_to "Back to friends", friends_path , class:"btn btn-secondary" %><br/><br/>

  <%= button_to "Destroy this friend", @friend, method: :delete,class:"btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends App', root_path, class: "navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
            <%= link_to 'About us', home_about_path, class:"nav-link text-white" %>
            
        </li>
        <li>
        <%= link_to 'Friends', friends_path, class:"nav-link text-white" %>
        </li>

        <li> <%= link_to "Add Friend", new_friend_path, class:"nav-link text-white" %> </li>
       
          <li class="navbar-text float-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, class:"nav-link" %> |
            


          <li><%= link_to "Destroy", destroy_user_session_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  },class:"nav-link" %>


          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class:"nav-link"  %> |
            <%= link_to "Login", new_user_session_path, class:"nav-link"  %>
          <% end %>
          </li>
        </ul>
          
      <form class="d-flex" role="search">
        <input class="form-control me-2 text-white" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success text-white" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> Hello World i am about Page </h1>

app/views/home/contact.html.erb
<h1> Hello World i am contact page </h1>

app/views/home/index.html.erb
<h1>Hello World</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <title>Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
  <%= render "home/header" %>
  <div class="container">
  <br/>
  <% if notice %>
  <%= render 'layouts/alerts' %>
  <% end %>

  </br>
  <%= yield %>    
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

app/views/models/_form.html.erb
<%= form_with(model: model) do |form| %>
  <% if model.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Buddies, style: "display: block" %>
    <%= form.text_field :Buddies %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/models/_model.html.erb
<div id="<%= dom_id model %>">
  <p>
    <strong>Buddies:</strong>
    <%= model.Buddies %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= model.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= model.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= model.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= model.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= model.twitter %>
  </p>

</div>

app/views/models/edit.html.erb
<h1>Editing model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Show this model", @model %> |
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Models</h1>

<div id="models">
  <% @models.each do |model| %>
    <%= render model %>
    <p>
      <%= link_to "Show this model", model %>
    </p>
  <% end %>
</div>

<%= link_to "New model", new_model_path %>

app/views/models/new.html.erb
<h1>New model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @model %>

<div>
  <%= link_to "Edit this model", edit_model_path(@model) %> |
  <%= link_to "Back to models", models_path %>

  <%= button_to "Destroy this model", @model, method: :delete %>
</div>